/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DiscountCodeInput {
    discountValue: number;
    expiresAt?: bigint;
    code: string;
    discountType: DiscountType;
    description: string;
    maxUses?: bigint;
    minimumOrderAmount: number;
}
export interface LoyaltyTransaction {
    id: bigint;
    createdAt: bigint;
    customerId: bigint;
    points: bigint;
    reason: string;
}
export interface AuditLog {
    id: bigint;
    action: string;
    timestamp: bigint;
    targetType: string;
    details: string;
    actorPrincipal: string;
    targetId?: bigint;
}
export interface TaxBreakdown {
    name: string;
    rate: number;
    amount: number;
}
export interface SaleOrderItem {
    itemId: bigint;
    quantity: bigint;
    price: number;
}
export interface StaffAccount {
    id: bigint;
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: StaffRole;
    isActive: boolean;
}
export interface SaleOrder {
    id: bigint;
    discountCodeId?: bigint;
    discountAmount: number;
    note: string;
    createdAt: bigint;
    taxTotal: number;
    totalAmount: number;
    taxBreakdown: Array<TaxBreakdown>;
    customerId?: bigint;
    items: Array<SaleOrderItem>;
    subtotal: number;
}
export interface DiscountCode {
    id: bigint;
    discountValue: number;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    discountType: DiscountType;
    usedCount: bigint;
    description: string;
    isActive: boolean;
    maxUses?: bigint;
    minimumOrderAmount: number;
}
export interface Customer {
    id: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    loyaltyPoints: bigint;
    phone: string;
}
export interface DiscountApplicationResult {
    discountCode: DiscountCode;
    discountAmount: number;
    finalTotal: number;
}
export interface TaxConfig {
    id: bigint;
    appliesTo: TaxAppliesTo;
    name: string;
    createdAt: bigint;
    rate: number;
    isActive: boolean;
}
export interface TaxCalculationResult {
    breakdown: Array<TaxBreakdown>;
    totalTaxAmount: number;
}
export interface TaxConfigInput {
    appliesTo: TaxAppliesTo;
    name: string;
    rate: number;
}
export enum DiscountType {
    fixed = "fixed",
    percentage = "percentage"
}
export enum StaffRole {
    manager = "manager",
    admin = "admin",
    cashier = "cashier"
}
export enum TaxAppliesTo {
    all = "all",
    menuItems = "menuItems",
    combos = "combos"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyDiscountCode(code: string, orderTotal: number): Promise<DiscountApplicationResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateTax(subtotal: number, targetType: string): Promise<TaxCalculationResult>;
    createCustomer(name: string, email: string, phone: string): Promise<bigint>;
    createDiscountCode(input: DiscountCodeInput): Promise<bigint>;
    createSaleOrder(items: Array<SaleOrderItem>, subtotal: number, totalAmount: number, discountAmount: number, taxBreakdown: Array<TaxBreakdown>, taxTotal: number, note: string, discountCodeId: bigint | null, customerId: bigint | null): Promise<bigint>;
    createStaffAccount(principal: Principal, name: string, role: StaffRole): Promise<void>;
    createTaxConfig(input: TaxConfigInput): Promise<bigint>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteDiscountCode(id: bigint): Promise<void>;
    deleteSaleOrder(id: bigint): Promise<void>;
    deleteStaffAccount(id: bigint): Promise<void>;
    deleteTaxConfig(id: bigint): Promise<void>;
    getAuditLogs(limit: bigint, offset: bigint): Promise<Array<AuditLog>>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getCustomerOrderHistory(customerId: bigint): Promise<Array<SaleOrder>>;
    getCustomers(): Promise<Array<Customer>>;
    getDiscountCode(id: bigint): Promise<DiscountCode | null>;
    getDiscountCodes(): Promise<Array<DiscountCode>>;
    getLoyaltyBalance(customerId: bigint): Promise<bigint>;
    getLoyaltyTransactions(customerId: bigint): Promise<Array<LoyaltyTransaction>>;
    getMyRole(): Promise<StaffRole | null>;
    getSaleOrder(id: bigint): Promise<SaleOrder | null>;
    getSaleOrders(): Promise<Array<SaleOrder>>;
    getStaffAccount(id: bigint): Promise<StaffAccount | null>;
    getStaffAccounts(): Promise<Array<StaffAccount>>;
    getTaxConfig(id: bigint): Promise<TaxConfig | null>;
    getTaxConfigs(): Promise<Array<TaxConfig>>;
    isCallerAdmin(): Promise<boolean>;
    redeemLoyaltyPoints(customerId: bigint, points: bigint, discountAmount: number): Promise<void>;
    toggleDiscountCode(id: bigint): Promise<void>;
    toggleTaxConfig(id: bigint): Promise<void>;
    updateCustomer(id: bigint, name: string, email: string, phone: string): Promise<void>;
    updateDiscountCode(id: bigint, input: DiscountCodeInput): Promise<void>;
    updateStaffAccount(id: bigint, name: string, role: StaffRole, isActive: boolean): Promise<void>;
    updateTaxConfig(id: bigint, input: TaxConfigInput): Promise<void>;
}
import type { AuditLog as _AuditLog, Customer as _Customer, DiscountApplicationResult as _DiscountApplicationResult, DiscountCode as _DiscountCode, DiscountCodeInput as _DiscountCodeInput, DiscountType as _DiscountType, SaleOrder as _SaleOrder, SaleOrderItem as _SaleOrderItem, StaffAccount as _StaffAccount, StaffRole as _StaffRole, TaxAppliesTo as _TaxAppliesTo, TaxBreakdown as _TaxBreakdown, TaxConfig as _TaxConfig, TaxConfigInput as _TaxConfigInput, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyDiscountCode(arg0: string, arg1: number): Promise<DiscountApplicationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.applyDiscountCode(arg0, arg1);
                return from_candid_DiscountApplicationResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyDiscountCode(arg0, arg1);
            return from_candid_DiscountApplicationResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateTax(arg0: number, arg1: string): Promise<TaxCalculationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTax(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTax(arg0, arg1);
            return result;
        }
    }
    async createCustomer(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async createDiscountCode(arg0: DiscountCodeInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiscountCode(to_candid_DiscountCodeInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiscountCode(to_candid_DiscountCodeInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSaleOrder(arg0: Array<SaleOrderItem>, arg1: number, arg2: number, arg3: number, arg4: Array<TaxBreakdown>, arg5: number, arg6: string, arg7: bigint | null, arg8: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSaleOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSaleOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async createStaffAccount(arg0: Principal, arg1: string, arg2: StaffRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaffAccount(arg0, arg1, to_candid_StaffRole_n16(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaffAccount(arg0, arg1, to_candid_StaffRole_n16(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createTaxConfig(arg0: TaxConfigInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTaxConfig(to_candid_TaxConfigInput_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTaxConfig(to_candid_TaxConfigInput_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteDiscountCode(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDiscountCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDiscountCode(arg0);
            return result;
        }
    }
    async deleteSaleOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSaleOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSaleOrder(arg0);
            return result;
        }
    }
    async deleteStaffAccount(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaffAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaffAccount(arg0);
            return result;
        }
    }
    async deleteTaxConfig(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTaxConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTaxConfig(arg0);
            return result;
        }
    }
    async getAuditLogs(arg0: bigint, arg1: bigint): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(arg0, arg1);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(arg0, arg1);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerOrderHistory(arg0: bigint): Promise<Array<SaleOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrderHistory(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrderHistory(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getDiscountCode(arg0: bigint): Promise<DiscountCode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscountCode(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscountCode(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiscountCodes(): Promise<Array<DiscountCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscountCodes();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscountCodes();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoyaltyBalance(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoyaltyBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoyaltyBalance(arg0);
            return result;
        }
    }
    async getLoyaltyTransactions(arg0: bigint): Promise<Array<LoyaltyTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoyaltyTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoyaltyTransactions(arg0);
            return result;
        }
    }
    async getMyRole(): Promise<StaffRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaleOrder(arg0: bigint): Promise<SaleOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaleOrder(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaleOrder(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaleOrders(): Promise<Array<SaleOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaleOrders();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaleOrders();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffAccount(arg0: bigint): Promise<StaffAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffAccount(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffAccount(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffAccounts(): Promise<Array<StaffAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffAccounts();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffAccounts();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaxConfig(arg0: bigint): Promise<TaxConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaxConfig(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaxConfig(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaxConfigs(): Promise<Array<TaxConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaxConfigs();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaxConfigs();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async redeemLoyaltyPoints(arg0: bigint, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemLoyaltyPoints(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemLoyaltyPoints(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleDiscountCode(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDiscountCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDiscountCode(arg0);
            return result;
        }
    }
    async toggleTaxConfig(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaxConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaxConfig(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateDiscountCode(arg0: bigint, arg1: DiscountCodeInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDiscountCode(arg0, to_candid_DiscountCodeInput_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDiscountCode(arg0, to_candid_DiscountCodeInput_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStaffAccount(arg0: bigint, arg1: string, arg2: StaffRole, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffAccount(arg0, arg1, to_candid_StaffRole_n16(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffAccount(arg0, arg1, to_candid_StaffRole_n16(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateTaxConfig(arg0: bigint, arg1: TaxConfigInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaxConfig(arg0, to_candid_TaxConfigInput_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaxConfig(arg0, to_candid_TaxConfigInput_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AuditLog_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLog): AuditLog {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountApplicationResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountApplicationResult): DiscountApplicationResult {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountCode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountCode): DiscountCode {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SaleOrder_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleOrder): SaleOrder {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_StaffAccount_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffAccount): StaffAccount {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_StaffRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffRole): StaffRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TaxAppliesTo_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaxAppliesTo): TaxAppliesTo {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TaxConfig_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaxConfig): TaxConfig {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiscountCode]): DiscountCode | null {
    return value.length === 0 ? null : from_candid_DiscountCode_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffRole]): StaffRole | null {
    return value.length === 0 ? null : from_candid_StaffRole_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SaleOrder]): SaleOrder | null {
    return value.length === 0 ? null : from_candid_SaleOrder_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffAccount]): StaffAccount | null {
    return value.length === 0 ? null : from_candid_StaffAccount_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaxConfig]): TaxConfig | null {
    return value.length === 0 ? null : from_candid_TaxConfig_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountCode: _DiscountCode;
    discountAmount: number;
    finalTotal: number;
}): {
    discountCode: DiscountCode;
    discountAmount: number;
    finalTotal: number;
} {
    return {
        discountCode: from_candid_DiscountCode_n3(_uploadFile, _downloadFile, value.discountCode),
        discountAmount: value.discountAmount,
        finalTotal: value.finalTotal
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: string;
    timestamp: bigint;
    targetType: string;
    details: string;
    actorPrincipal: string;
    targetId: [] | [bigint];
}): {
    id: bigint;
    action: string;
    timestamp: bigint;
    targetType: string;
    details: string;
    actorPrincipal: string;
    targetId?: bigint;
} {
    return {
        id: value.id,
        action: value.action,
        timestamp: value.timestamp,
        targetType: value.targetType,
        details: value.details,
        actorPrincipal: value.actorPrincipal,
        targetId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.targetId))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    discountCodeId: [] | [bigint];
    discountAmount: number;
    note: string;
    createdAt: bigint;
    taxTotal: number;
    totalAmount: number;
    taxBreakdown: Array<_TaxBreakdown>;
    customerId: [] | [bigint];
    items: Array<_SaleOrderItem>;
    subtotal: number;
}): {
    id: bigint;
    discountCodeId?: bigint;
    discountAmount: number;
    note: string;
    createdAt: bigint;
    taxTotal: number;
    totalAmount: number;
    taxBreakdown: Array<TaxBreakdown>;
    customerId?: bigint;
    items: Array<SaleOrderItem>;
    subtotal: number;
} {
    return {
        id: value.id,
        discountCodeId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.discountCodeId)),
        discountAmount: value.discountAmount,
        note: value.note,
        createdAt: value.createdAt,
        taxTotal: value.taxTotal,
        totalAmount: value.totalAmount,
        taxBreakdown: value.taxBreakdown,
        customerId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.customerId)),
        items: value.items,
        subtotal: value.subtotal
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: _StaffRole;
    isActive: boolean;
}): {
    id: bigint;
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: StaffRole;
    isActive: boolean;
} {
    return {
        id: value.id,
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_StaffRole_n34(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    discountValue: number;
    expiresAt: [] | [bigint];
    code: string;
    createdAt: bigint;
    discountType: _DiscountType;
    usedCount: bigint;
    description: string;
    isActive: boolean;
    maxUses: [] | [bigint];
    minimumOrderAmount: number;
}): {
    id: bigint;
    discountValue: number;
    expiresAt?: bigint;
    code: string;
    createdAt: bigint;
    discountType: DiscountType;
    usedCount: bigint;
    description: string;
    isActive: boolean;
    maxUses?: bigint;
    minimumOrderAmount: number;
} {
    return {
        id: value.id,
        discountValue: value.discountValue,
        expiresAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.expiresAt)),
        code: value.code,
        createdAt: value.createdAt,
        discountType: from_candid_DiscountType_n6(_uploadFile, _downloadFile, value.discountType),
        usedCount: value.usedCount,
        description: value.description,
        isActive: value.isActive,
        maxUses: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.maxUses)),
        minimumOrderAmount: value.minimumOrderAmount
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    appliesTo: _TaxAppliesTo;
    name: string;
    createdAt: bigint;
    rate: number;
    isActive: boolean;
}): {
    id: bigint;
    appliesTo: TaxAppliesTo;
    name: string;
    createdAt: bigint;
    rate: number;
    isActive: boolean;
} {
    return {
        id: value.id,
        appliesTo: from_candid_TaxAppliesTo_n44(_uploadFile, _downloadFile, value.appliesTo),
        name: value.name,
        createdAt: value.createdAt,
        rate: value.rate,
        isActive: value.isActive
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    cashier: null;
}): StaffRole {
    return "manager" in value ? StaffRole.manager : "admin" in value ? StaffRole.admin : "cashier" in value ? StaffRole.cashier : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    menuItems: null;
} | {
    combos: null;
}): TaxAppliesTo {
    return "all" in value ? TaxAppliesTo.all : "menuItems" in value ? TaxAppliesTo.menuItems : "combos" in value ? TaxAppliesTo.combos : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: null;
} | {
    percentage: null;
}): DiscountType {
    return "fixed" in value ? DiscountType.fixed : "percentage" in value ? DiscountType.percentage : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SaleOrder>): Array<SaleOrder> {
    return value.map((x)=>from_candid_SaleOrder_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiscountCode>): Array<DiscountCode> {
    return value.map((x)=>from_candid_DiscountCode_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffAccount>): Array<StaffAccount> {
    return value.map((x)=>from_candid_StaffAccount_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaxConfig>): Array<TaxConfig> {
    return value.map((x)=>from_candid_TaxConfig_n42(_uploadFile, _downloadFile, x));
}
function to_candid_DiscountCodeInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountCodeInput): _DiscountCodeInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_DiscountType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_StaffRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): _StaffRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TaxAppliesTo_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaxAppliesTo): _TaxAppliesTo {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_TaxConfigInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaxConfigInput): _TaxConfigInput {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountValue: number;
    expiresAt?: bigint;
    code: string;
    discountType: DiscountType;
    description: string;
    maxUses?: bigint;
    minimumOrderAmount: number;
}): {
    discountValue: number;
    expiresAt: [] | [bigint];
    code: string;
    discountType: _DiscountType;
    description: string;
    maxUses: [] | [bigint];
    minimumOrderAmount: number;
} {
    return {
        discountValue: value.discountValue,
        expiresAt: value.expiresAt ? candid_some(value.expiresAt) : candid_none(),
        code: value.code,
        discountType: to_candid_DiscountType_n13(_uploadFile, _downloadFile, value.discountType),
        description: value.description,
        maxUses: value.maxUses ? candid_some(value.maxUses) : candid_none(),
        minimumOrderAmount: value.minimumOrderAmount
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appliesTo: TaxAppliesTo;
    name: string;
    rate: number;
}): {
    appliesTo: _TaxAppliesTo;
    name: string;
    rate: number;
} {
    return {
        appliesTo: to_candid_TaxAppliesTo_n20(_uploadFile, _downloadFile, value.appliesTo),
        name: value.name,
        rate: value.rate
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    fixed: null;
} | {
    percentage: null;
} {
    return value == DiscountType.fixed ? {
        fixed: null
    } : value == DiscountType.percentage ? {
        percentage: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): {
    manager: null;
} | {
    admin: null;
} | {
    cashier: null;
} {
    return value == StaffRole.manager ? {
        manager: null
    } : value == StaffRole.admin ? {
        admin: null
    } : value == StaffRole.cashier ? {
        cashier: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaxAppliesTo): {
    all: null;
} | {
    menuItems: null;
} | {
    combos: null;
} {
    return value == TaxAppliesTo.all ? {
        all: null
    } : value == TaxAppliesTo.menuItems ? {
        menuItems: null
    } : value == TaxAppliesTo.combos ? {
        combos: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
