/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InventoryItem = IDL.Record({
  'lowStockThreshold' : IDL.Float64,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Float64,
  'costPricePerUnit' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InventoryResponse = IDL.Record({
  'lowStockThreshold' : IDL.Float64,
  'totalValue' : IDL.Float64,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Float64,
  'costPricePerUnit' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInventoryItem' : IDL.Func([InventoryItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInventoryStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalValue' : IDL.Float64,
          'lowStockCount' : IDL.Nat,
          'totalItems' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryResponse)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listInventory' : IDL.Func([], [IDL.Vec(InventoryResponse)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInventoryItem' : IDL.Func([IDL.Text, InventoryItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InventoryItem = IDL.Record({
    'lowStockThreshold' : IDL.Float64,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Float64,
    'costPricePerUnit' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InventoryResponse = IDL.Record({
    'lowStockThreshold' : IDL.Float64,
    'totalValue' : IDL.Float64,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Float64,
    'costPricePerUnit' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInventoryItem' : IDL.Func([InventoryItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInventoryStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalValue' : IDL.Float64,
            'lowStockCount' : IDL.Nat,
            'totalItems' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryResponse)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listInventory' : IDL.Func([], [IDL.Vec(InventoryResponse)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInventoryItem' : IDL.Func([IDL.Text, InventoryItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };