/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LoyaltyTransaction {
  'id' : bigint,
  'createdAt' : bigint,
  'customerId' : bigint,
  'points' : bigint,
  'reason' : string,
}
export interface SaleOrder {
  'id' : bigint,
  'discountCodeId' : [] | [bigint],
  'discountAmount' : number,
  'note' : string,
  'createdAt' : bigint,
  'taxTotal' : number,
  'totalAmount' : number,
  'taxBreakdown' : Array<TaxBreakdown>,
  'customerId' : [] | [bigint],
  'items' : Array<SaleOrderItem>,
  'subtotal' : number,
}
export interface SaleOrderItem {
  'itemId' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export interface TaxBreakdown {
  'name' : string,
  'rate' : number,
  'amount' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSaleOrder' : ActorMethod<
    [
      Array<SaleOrderItem>,
      number,
      number,
      number,
      Array<TaxBreakdown>,
      number,
      string,
      [] | [bigint],
      [] | [bigint],
    ],
    bigint
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrderHistory' : ActorMethod<[bigint], Array<SaleOrder>>,
  'getLoyaltyBalance' : ActorMethod<[bigint], bigint>,
  'getLoyaltyTransactions' : ActorMethod<[bigint], Array<LoyaltyTransaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemLoyaltyPoints' : ActorMethod<[bigint, bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];