/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InventoryItem {
  'lowStockThreshold' : number,
  'supplier' : string,
  'name' : string,
  'unit' : string,
  'quantity' : number,
  'costPricePerUnit' : number,
}
export interface InventoryResponse {
  'lowStockThreshold' : number,
  'totalValue' : number,
  'supplier' : string,
  'name' : string,
  'unit' : string,
  'quantity' : number,
  'costPricePerUnit' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventoryStats' : ActorMethod<
    [],
    { 'totalValue' : number, 'lowStockCount' : bigint, 'totalItems' : bigint }
  >,
  'getLowStockItems' : ActorMethod<[], Array<InventoryResponse>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listInventory' : ActorMethod<[], Array<InventoryResponse>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventoryItem' : ActorMethod<[string, InventoryItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];